### PR TITLE
Half Repetitions

### PR DESCRIPTION
**Pull request by etwest**

### CODE REVIEW

**Comment by etwest** [comment]
Kenny - The change I made here is correct for half repetitions right? 

If so, why are tests failing and how can we address that issue?

**Comment by kennyzzhang** [comment]
Ah, the sampling test is still comparing against a fixed probability. A quick fix is to go into sketch_test.cpp, and for SketchTestSample and SketchTestAddition, explicitly set bucket repetitions to 1.

**Comment by etwest** [comment]
Okay so these failing tests aren't an indication of something wrong right? If so can we get this pull request approved and merged?

**Comment by Victor-C-Zhang** [comment]
I'd be a little more at ease if we set the probability based on repetitions, but in the interest of time I think this is fine. I've opened an issue for this that should be resolved once we're out of crunch mode.

**Review by Victor-C-Zhang — APPROVED** [review]
See comment and related issue

**Pull request merged**
