### PR TITLE
feat: fast hash function

### PR DESCRIPTION
**Pull request by Victor-C-Zhang**
`xxhash` is fast for variable-length digests but not optimized for our purposes. `xxPMS` is a hash function designed specifically for 64-bit inputs and 64/32-bit outputs. It is a bespoke hash that borrows from `xxh3`'s mixing steps and other fast universal hashing schemes. With `xxPMS`, CC time is reduced by an order of magnitude and insertion speed increases by almost half, with no noticeable increase in failure rate.

### (Some) Experimental Results
Current system numbers are in (parentheses).
On kron17, no memory limit; 5.01m (4.41m) ins/sec, 0.27s (0.29s) CC time.
Ran `xxhash_bench` benchmark with parameters `1000000 8 10`; 32 bit 5.3e7 (2.8e7) hashes/sec, 64 bit 6.1e7 (2.5e7) hashes/sec.
Ran continuous correctness test 50 times, 10 CCs each with no failures.

EDIT (Evan): Updated previous results based upon a speed experiment ran today.

### TODO
- [x] Put `xxhash_bench` and other experimental files into `ZeppelinExperiments` repo
- [x] Remove dependency on xxhash
- [ ] Answer questions in last comment

### CODE REVIEW

**Comment by etwest** [comment]
xxhash_bench should probably just be dissolved and incorporated into the benchmarking code rather than moved into the experiments repo.

**Comment by etwest** [comment]
What were the parameters you used for running the kron17 test? gutter_factor can have a big impact on performance. For the speed experiments in memory the standard value is -2

**Comment by etwest** [comment]
> What were the parameters you used for running the kron17 test? gutter_factor can have a big impact on performance. For the speed experiments in memory the standard value is -2

It actually would probably be better to compare the speed of updating and querying the sketches using the benchmarking tools that I developed. That way we can avoid problems around buffering and other factors that might obfuscate the impact of this hash function.

**Comment by Victor-C-Zhang** [comment]
> > What were the parameters you used for running the kron17 test? gutter_factor can have a big impact on performance. For the speed experiments in memory the standard value is -2
> 
> It actually would probably be better to compare the speed of updating and querying the sketches using the benchmarking tools that I developed. That way we can avoid problems around buffering and other factors that might obfuscate the impact of this hash function.

I used the default values for speed experiment. I’ll run the benchmark after it’s merged in.

**Comment by Victor-C-Zhang** [comment]
Current main head
```
BM_Hash_XXH64/1                   20.8 ns         20.8 ns     33613092 Hashes=48.1267M/s
BM_Hash_XXH64/100                 1944 ns         1944 ns       356678 Hashes=51.4345M/s
BM_Hash_XXH64/10000             190762 ns       190756 ns         3645 Hashes=52.423M/s
BM_Hash_XXH3_64/1                 15.6 ns         15.6 ns     45222631 Hashes=64.1972M/s
BM_Hash_XXH3_64/100               1082 ns         1082 ns       646655 Hashes=92.3888M/s
BM_Hash_XXH3_64/10000           103137 ns       103136 ns         6818 Hashes=96.9594M/s
BM_Hash_bucket/1                  20.8 ns         20.8 ns     33607241 Hashes=48.095M/s
BM_Hash_bucket/100                1941 ns         1941 ns       359807 Hashes=51.5289M/s
BM_Hash_bucket/10000            189249 ns       189248 ns         3649 Hashes=52.8407M/s
BM_Sketch_Update/16384/0    1057400470 ns   1057362063 ns            1 Update_Rate=9.4575M/s
BM_Sketch_Update/65536/0    1090665905 ns   1090600098 ns            1 Update_Rate=9.16926M/s
BM_Sketch_Update/262144/0   1123309137 ns   1123254426 ns            1 Update_Rate=8.9027M/s
BM_Sketch_Update/1048576/0  1121727101 ns   1121662737 ns            1 Update_Rate=8.91534M/s
BM_Sketch_Update/4194304/0  1138982375 ns   1138961307 ns            1 Update_Rate=8.77993M/s
BM_Sketch_Update/16777216/0 1151034472 ns   1150984221 ns            1 Update_Rate=8.68822M/s
BM_Sketch_Update/16384/1     952903745 ns    952855210 ns            1 Update_Rate=10.4948M/s
BM_Sketch_Update/65536/1     954500690 ns    954478994 ns            1 Update_Rate=10.4769M/s
BM_Sketch_Update/262144/1    959018966 ns    958982311 ns            1 Update_Rate=10.4277M/s
BM_Sketch_Update/1048576/1   955503515 ns    955473877 ns            1 Update_Rate=10.466M/s
BM_Sketch_Update/4194304/1   953316077 ns    953245529 ns            1 Update_Rate=10.4905M/s
BM_Sketch_Update/16777216/1  957062331 ns    957051638 ns            1 Update_Rate=10.4488M/s
BM_Sketch_Query/0                  495 ns          495 ns      1391675 Query_Rate=202.074M/s
BM_Sketch_Query/10                5080 ns         5080 ns       137203 Query_Rate=19.6842M/s
BM_Sketch_Query/20                6139 ns         6139 ns       111851 Query_Rate=16.2898M/s
BM_Sketch_Query/30                8066 ns         8066 ns        87252 Query_Rate=12.3978M/s
BM_Sketch_Query/40                8777 ns         8777 ns        80205 Query_Rate=11.3929M/s
BM_Sketch_Query/50               11444 ns        11444 ns        61430 Query_Rate=8.73815M/s
BM_Sketch_Query/60               12406 ns        12405 ns        56264 Query_Rate=8.06107M/s
BM_Sketch_Query/70               14282 ns        14282 ns        48767 Query_Rate=7.00191M/s
BM_Sketch_Query/80               16879 ns        16879 ns        41588 Query_Rate=5.92448M/s
BM_Sketch_Query/90               19047 ns        19046 ns        36914 Query_Rate=5.25033M/s
```
xxhash_bench head
```
BM_Hash_XXH64/1                   14.8 ns         14.8 ns     47422964 Hashes=67.6885M/s
BM_Hash_XXH64/100                 1477 ns         1477 ns       469389 Hashes=67.6996M/s
BM_Hash_XXH64/10000             142649 ns       142646 ns         4946 Hashes=70.1035M/s
BM_Hash_XXH3_64/1                 15.5 ns         15.5 ns     45419984 Hashes=64.5448M/s
BM_Hash_XXH3_64/100               1094 ns         1094 ns       632587 Hashes=91.3761M/s
BM_Hash_XXH3_64/10000           102873 ns       102870 ns         6658 Hashes=97.2097M/s
BM_Hash_XXPMS64/1                 18.5 ns         18.5 ns     37771390 Hashes=53.9298M/s
BM_Hash_XXPMS64/100               1876 ns         1876 ns       371326 Hashes=53.3105M/s
BM_Hash_XXPMS64/10000           183102 ns       183100 ns         3820 Hashes=54.615M/s
BM_Hash_bucket/1                  22.9 ns         22.9 ns     30460025 Hashes=43.5794M/s
BM_Hash_bucket/100                2294 ns         2294 ns       306208 Hashes=43.5853M/s
BM_Hash_bucket/10000            224998 ns       224990 ns         3132 Hashes=44.4465M/s
BM_Sketch_Update/16384/0     931490284 ns    931476553 ns            1 Update_Rate=10.7356M/s
BM_Sketch_Update/65536/0     950457750 ns    950420274 ns            1 Update_Rate=10.5217M/s
BM_Sketch_Update/262144/0    980875301 ns    980863850 ns            1 Update_Rate=10.1951M/s
BM_Sketch_Update/1048576/0  1010711298 ns   1010686505 ns            1 Update_Rate=9.89426M/s
BM_Sketch_Update/4194304/0  1040090155 ns   1040066469 ns            1 Update_Rate=9.61477M/s
BM_Sketch_Update/16777216/0 1069299996 ns   1069254460 ns            1 Update_Rate=9.35231M/s
BM_Sketch_Update/16384/1     809630335 ns    809607094 ns            1 Update_Rate=12.3517M/s
BM_Sketch_Update/65536/1     812181245 ns    812136429 ns            1 Update_Rate=12.3132M/s
BM_Sketch_Update/262144/1    803282415 ns    803249717 ns            1 Update_Rate=12.4494M/s
BM_Sketch_Update/1048576/1   806314498 ns    806265994 ns            1 Update_Rate=12.4029M/s
BM_Sketch_Update/4194304/1   800043313 ns    800034168 ns            1 Update_Rate=12.4995M/s
BM_Sketch_Update/16777216/1  791389392 ns    791322961 ns            1 Update_Rate=12.6371M/s
BM_Sketch_Query/0                  467 ns          467 ns      1482770 Query_Rate=214.358M/s
BM_Sketch_Query/10                8286 ns         8286 ns        85943 Query_Rate=12.0686M/s
BM_Sketch_Query/20                8708 ns         8708 ns        79866 Query_Rate=11.4837M/s
BM_Sketch_Query/30               11309 ns        11309 ns        62107 Query_Rate=8.84274M/s
BM_Sketch_Query/40               13697 ns        13697 ns        51271 Query_Rate=7.30081M/s
BM_Sketch_Query/50               16292 ns        16291 ns        43216 Query_Rate=6.13818M/s
BM_Sketch_Query/60               19570 ns        19570 ns        36060 Query_Rate=5.1099M/s
BM_Sketch_Query/70               21107 ns        21107 ns        32901 Query_Rate=4.73781M/s
BM_Sketch_Query/80               23651 ns        23651 ns        29719 Query_Rate=4.22812M/s
BM_Sketch_Query/90               29159 ns        29159 ns        23976 Query_Rate=3.42948M/s
```

**Comment by Victor-C-Zhang** [comment]
Looks like the benchmarks say we're slower but kron17 says we're faster?

**Comment by etwest** [comment]
> Looks like the benchmarks say we're slower but kron17 says we're faster?

Thanks for including the benchmark results. I'm a little confused about what they're saying though. Can you edit the comment to include details about what exactly is being tested in each run? Also, what machine did you run the benchmark on?

**Comment by Victor-C-Zhang** [comment]
> > Looks like the benchmarks say we're slower but kron17 says we're faster?
> 
> Thanks for including the benchmark results. I'm a little confused about what they're saying though. Can you edit the comment to include details about what exactly is being tested in each run? Also, what machine did you run the benchmark on?

Bigboy, just now.

**Comment by Victor-C-Zhang** [comment]
Speed experiment results:
```
Procesing 4474931789 updates took 943.194 seconds, 4.74444e+06 per second
Connected Components algorithm took 0.281539 and found 101 CC
```
On `kron17` with no limit, standalone, settings
```
buffering.conf
buffer_exp=23
branch=512
queue_factor=-2
page_factor=5
num_threads=1
gutter_factor=-20

streaming.conf
buffering_system=standalone
path_prefix=./GUTTREEDATA/
num_groups=46
group_size=1
```
It seems we're still faster for ingestion on kron17, but not really for CC time.

**Comment by Victor-C-Zhang** [comment]
Ran on kron15 with similar results: ingestion is faster, CC time marginally faster.
```
Procesing 280025434 updates took 50.8665 seconds, 5.50511e+06 per second
Connected Components algorithm took 0.0622137 and found 51 CC
```
Running with gutter tree on kron17 yields similar results:
```
Procesing 4474931789 updates took 944.816 seconds, 4.7363e+06 per second
Connected Components algorithm took 0.278742 and found 101 CC
```

**Comment by etwest** [comment]
> Speed experiment results:
> 
> ```
> Procesing 4474931789 updates took 943.194 seconds, 4.74444e+06 per second
> Connected Components algorithm took 0.281539 and found 101 CC
> ```
> 
> On `kron17` with no limit, standalone, settings
> 
> ```
> buffering.conf
> buffer_exp=23
> branch=512
> queue_factor=-2
> page_factor=5
> num_threads=1
> gutter_factor=-20
> 
> streaming.conf
> buffering_system=standalone
> path_prefix=./GUTTREEDATA/
> num_groups=46
> group_size=1
> ```
> 
> It seems we're still faster for ingestion on kron17, but not really for CC time.

Ah so this is not the default configuration or at least it shouldn’t be. Try running with a gutter factor of -2. 
Although if you’re running both systems with this configuration maybe it doesn’t matter, but if you’re comparing to the results in the wiki than it does.

**Comment by Victor-C-Zhang** [comment]
> Ah so this is not the default configuration or at least it shouldn’t be. Try running with a gutter factor of -2. Although if you’re running both systems with this configuration maybe it doesn’t matter, but if you’re comparing to the results in the wiki than it does.

With gutter factor -2 (and queue factor 8, oops) things are slightly worse, but not by much:
```
Procesing 4474931789 updates took 960.414 seconds, 4.65938e+06 per second
Connected Components algorithm took 0.301509 and found 101 CC
```

**Comment by etwest** [comment]
```
---------------------------------------------------------------------------------------
Benchmark                Repetitions Hashes_main       Hashes_XXPMS64    Hashes_XXH3_64
---------------------------------------------------------------------------------------
BM_Hash_XXH64/1_mean               5   47.9959M/s       67.9303M/s       67.628M/s
BM_Hash_XXH64/100_mean             5   51.5062M/s       67.7861M/s       67.6524M/s
BM_Hash_XXH64/10000_mean           5   52.7693M/s       70.2523M/s       70.1115M/s
BM_Hash_XXH3_64/1_mean             5   64.5798M/s       64.5399M/s       64.4564M/s
BM_Hash_XXH3_64/100_mean           5   92.4177M/s       92.2922M/s       92.3314M/s
BM_Hash_XXH3_64/10000_mean         5   97.1728M/s       97.263M/s        97.0853M/s
BM_Hash_XXPMS64/1_mean             5          N/A       53.9196M/s       N/A
BM_Hash_XXPMS64100_mean            5          N/A       53.3617M/s       N/A
BM_Hash_XXPMS64/10000_mean         5          N/A       54.6826M/s       N/A
BM_Hash_bucket/1_mean              5   48.0699M/s       43.8336M/s       64.4139M/s
BM_Hash_bucket/100_mean            5     51.39M/s       43.8274M/s       92.2989M/s
BM_Hash_bucket/10000_mean          5    53.061M/s       44.8487M/s       96.9539M/s
---------------------------------------------------------------------------------------
Benchmark                Repetitions Update_Rate_main   Update_Rate_XXPMS64   Update_Rate_XXH3_64
---------------------------------------------------------------------------------------
BM_Sketch_Update/16384/0_mean      5    9.47932M/s       10.7374M/s           9.70611M/s
BM_Sketch_Update/65536/0_mean      5    9.12165M/s       10.2083M/s           9.38851M/s
BM_Sketch_Update/262144/0_mean     5    8.77617M/s       9.96944M/s           9.04759M/s
BM_Sketch_Update/1048576/0_mean    5     8.6608M/s       9.60392M/s           8.94152M/s
BM_Sketch_Update/4194304/0_mean    5    8.58171M/s       9.40227M/s           8.81611M/s
BM_Sketch_Update/16777216/0_mean   5    8.49086M/s       9.28146M/s           8.75175M/s
BM_Sketch_Update/16384/1_mean      5    10.4791M/s       12.6258M/s           10.8598M/s
BM_Sketch_Update/65536/1_mean      5      10.46M/s       12.6509M/s           10.8907M/s
BM_Sketch_Update/262144/1_mean     5    10.3615M/s       12.6758M/s           10.8772M/s
BM_Sketch_Update/1048576/1_mean    5    10.4265M/s       12.6445M/s           10.7211M/s
BM_Sketch_Update/4194304/1_mean    5    10.4289M/s       12.6223M/s           10.8353M/s
BM_Sketch_Update/16777216/1_mean   5    10.4426M/s       12.6068M/s           10.8574M/s
---------------------------------------------------------------------------------------
Benchmark                Repetitions Query_Rate_main   Query_Rate_XXPMS64    Query_Rate_XXH3_64
---------------------------------------------------------------------------------------
BM_Sketch_Query/0_mean             5   199.364M/s         212.406M/s         187.491M/s
BM_Sketch_Query/10_mean            5   19.3742M/s         12.2525M/s         19.2184M/s
BM_Sketch_Query/20_mean            5   16.4566M/s         11.3952M/s         15.9753M/s
BM_Sketch_Query/30_mean            5   12.4291M/s         8.85176M/s         12.7769M/s
BM_Sketch_Query/40_mean            5    11.402M/s         7.28011M/s         11.4921M/s
BM_Sketch_Query/50_mean            5   8.70705M/s         6.11755M/s         9.76946M/s
BM_Sketch_Query/60_mean            5   8.07005M/s         5.12165M/s         8.24621M/s
BM_Sketch_Query/70_mean            5   6.98337M/s         4.73043M/s         7.48802M/s
BM_Sketch_Query/80_mean            5   5.92971M/s         4.22237M/s         6.798M/s
BM_Sketch_Query/90_mean            5   5.24158M/s         3.41901M/s         6.14625M/s
```

I reran the benchmark with each benchmark run 5 times to establish a mean. The results seem the same so I can be confident that some weird behavior I'm seeing isn't an artifact. I have a number of questions.

- [ ] Why is the XXH64 benchmark significantly faster on this branch than on main?
- [ ] It looks like the best performance is found with XXH3_64. Have we tried using that for bucket_boruvka rather than XXPMS64? What's the difference in performance?
- [ ] Any guesses as to why the queries are slower but the updates are faster when using your hash?

**Comment by Victor-C-Zhang** [comment]
> I reran the benchmark with each benchmark run 5 times to establish a mean. The results seem the same so I can be confident that some weird behavior I'm seeing isn't an artifact. I have a number of questions.
> 
> * [x]  Why is the XXH64 benchmark significantly faster on this branch than on main?
> * [x]  It looks like the best performance is found with XXH3_64. Have we tried using that for bucket_boruvka rather than XXPMS64? What's the difference in performance?
> * [x]  Any guesses as to why the queries are slower but the updates are faster when using your hash?

- I have no idea. These should represent purely xxhash behavior. Maybe xxhash has had an update since you pulled; did you build from scratch for both experiments?
- I assume that since we're using XXH64 and not XXH3 (which is advertised to be faster), we have a good reason. Am I mistaken?
- I honestly have no idea. I'm not too sure how much I trust these benchmark results either, since
    - `xxhash_bench` shows our hashes are much faster than xxhash (and google bench shows we are slower)
    - Hash rate should be positively correlated with update speed but the google bench results show the opposite
    - Empirical tests show we are about as fast on queries as main (and google bench shows we're significantly slower)

**Comment by etwest** [comment]
> * I have no idea. These should represent purely xxhash behavior. Maybe xxhash has had an update since you pulled; did you build from scratch for both experiments?
> * I assume that since we're using XXH64 and not XXH3 (which is advertised to be faster), we have a good reason. Am I mistaken?
> * I honestly have no idea. I'm not too sure how much I trust these benchmark results either, since
>   
>   * `xxhash_bench` shows our hashes are much faster than xxhash (and google bench shows we are slower)
>   * Hash rate should be positively correlated with update speed but the google bench results show the opposite
>   * Empirical tests show we are about as fast on queries as main (and google bench shows we're significantly slower)

1. Could be a difference in how xxhash is being linked since its not routing through GraphStreamingCC anymore...
2. I don't know of any reason why we use XXH64 and not XXH3_64bits.
3. Something is definitely weird here. The benchmark design might not be quite measuring what we think it is but on main everything seems to me correlating as we expect so I'm not sure its entirely the benchmark's fault.

**Comment by Victor-C-Zhang** [comment]
> 1. Could be a difference in how xxhash is being linked since its not routing through GraphStreamingCC anymore...
> 2. I don't know of any reason why we use XXH64 and not XXH3_64bits.
> 3. Something is definitely weird here. The benchmark design might not be quite measuring what we think it is but on main everything seems to me correlating as we expect so I'm not sure its entirely the benchmark's fault.

1. I think this might be it. I'll try reverting `CMakeLists` to how it is on main to confirm.
2. I'll try running some experiments with XXH3 to see how we do.
3. I think this might be an artifact of (1). Our results would make sense if we take the values from main. We'll see how things go.

**Comment by Victor-C-Zhang** [comment]
Another thing I haven't done in this PR is change our function calls from passing via indirection (`type&`) to passing by value. I think we may be able to see some improvements depending on how smart the compiler is on the machines we test on.

**Comment by Victor-C-Zhang** [comment]
```
BM_Hash_XXH64/1_mean                     12.4 ns         12.4 ns            5 Hashes=80.7635M/s
BM_Hash_XXH64/100_mean                   1156 ns         1156 ns            5 Hashes=86.5425M/s
BM_Hash_XXH64/10000_mean               111230 ns       111229 ns            5 Hashes=89.9051M/s
BM_Hash_XXH3_64/1_mean                   15.4 ns         15.4 ns            5 Hashes=64.8099M/s
BM_Hash_XXH3_64/100_mean                 1079 ns         1079 ns            5 Hashes=92.7057M/s
BM_Hash_XXH3_64/10000_mean             102493 ns       102492 ns            5 Hashes=97.5688M/s
BM_Hash_XXPMS64/1_mean                   23.0 ns         23.0 ns            5 Hashes=43.4498M/s
BM_Hash_XXPMS64/100_mean                 2276 ns         2276 ns            5 Hashes=43.9295M/s
BM_Hash_XXPMS64/10000_mean             222231 ns       222229 ns            5 Hashes=44.9988M/s
```
Put xxhash back into GraphStreamingCC. No idea why, but benchmarks just seem faster now and PMS worse by comparison.
```
PMS on kron17 standalone
Procesing 4474931789 updates took 944.418 seconds, 4.7383e+06 per second
Connected Components algorithm took 0.275709 and found 101 CC

XXH3 on kron17 standalone
Procesing 4474931789 updates took 987.946 seconds, 4.52953e+06 per second
Connected Components algorithm took 0.290113 and found 101 CC

Main on kron17 standalone
Procesing 4474931789 updates took 1014.02 seconds, 4.41306e+06 per second
Connected Components algorithm took 0.287195 and found 101 CC
```
XXH3 helps a little bit, but PMS hash is still faster.

**Comment by etwest** [comment]
This is super out of date and we are getting superb performance without it. I'm closing for the moment. We can revisit later if we need more juice.

**Pull request closed without merging**
